'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Cliente
    Public Property ClienteID As Integer
    Public Property NroDocumento As String
    Public Property NombreApelllido As String
    Public Property CiudadID As Nullable(Of Integer)
    Public Property Direccion As String
    Public Property Telefono As String
    Public Property EstaActivo As String

    Public Overridable Property Ciudad As Ciudad
    Public Overridable Property Mascota As ICollection(Of Mascota) = New HashSet(Of Mascota)

End Class
