'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class DetalleVenta
    Public Property DetalleVentaID As Integer
    Public Property VentaID As Integer
    Public Property ProductoID As Integer
    Public Property Cantidad As Integer

    Public Overridable Property Producto As Producto
    Public Overridable Property Venta As Venta

End Class
