'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Especie
    Public Property EspecieID As Integer
    Public Property Descripcion As String
    Public Property EstaActivo As String

    Public Overridable Property Mascota As ICollection(Of Mascota) = New HashSet(Of Mascota)

End Class
