'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class MascotaVacuna
    Public Property MascotaVacunaID As Integer
    Public Property MascotaID As Integer
    Public Property VacunaID As Integer
    Public Property FechaVacunacion As Date
    Public Property FechaProximaVacunacion As Nullable(Of Date)
    Public Property Costo As Nullable(Of Decimal)

    Public Overridable Property Mascota As Mascota
    Public Overridable Property Vacuna As Vacuna

End Class
