'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Mascota
    Public Property MascotaID As Integer
    Public Property ClienteID As Integer
    Public Property Nombre As String
    Public Property RazaID As Integer
    Public Property FechaNacimiento As Date
    Public Property Sexo As String
    Public Property EspecieID As Nullable(Of Integer)
    Public Property EstaActivo As String

    Public Overridable Property Cliente As Cliente
    Public Overridable Property Especie As Especie
    Public Overridable Property Raza As Raza
    Public Overridable Property MascotaVacuna As ICollection(Of MascotaVacuna) = New HashSet(Of MascotaVacuna)

End Class
