'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Venta
    Public Property VentaID As Integer
    Public Property FechaVenta As Date
    Public Property ClienteID As Integer

    Public Overridable Property Cliente As Cliente
    Public Overridable Property DetalleVenta As ICollection(Of DetalleVenta) = New HashSet(Of DetalleVenta)

End Class
