'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class VeterinariaEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=VeterinariaEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property Ciudad() As DbSet(Of Ciudad)
    Public Overridable Property Cliente() As DbSet(Of Cliente)
    Public Overridable Property Especie() As DbSet(Of Especie)
    Public Overridable Property Mascota() As DbSet(Of Mascota)
    Public Overridable Property MascotaVacuna() As DbSet(Of MascotaVacuna)
    Public Overridable Property Raza() As DbSet(Of Raza)
    Public Overridable Property Vacuna() As DbSet(Of Vacuna)
    Public Overridable Property DetalleVenta() As DbSet(Of DetalleVenta)
    Public Overridable Property Producto() As DbSet(Of Producto)
    Public Overridable Property Venta() As DbSet(Of Venta)

End Class
